# Optional annotato config.
# Copy to $XDG_CONFIG_HOME/annotato/config.toml or ~/.config/annotato/config.toml.

[keybindings]
next = { primary = "Space" }
previous = { primary = "Space", modifiers = ["shift"] }
save = { primary = "S" }
edit = { primary = "E" }
draw = { primary = "B" }
move_box = { primary = "M" }
class_popup = { primary = "C" }
temporary_focus = { primary = "F" }
confirm = { primary = "Enter" }
abort = { primary = "Escape" }
delete = { primary = "Delete" }
