FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt update -y && \
    apt install -y \
    gdebi-core \
    libqt5widgets5 \
    libfmt-dev \
    libgvc6 \
    libsdl2-dev \
    curl

# Needed for the webots-controller libraries
RUN curl -sLO https://github.com/cyberbotics/webots/releases/download/R2023b/webots_2023b_amd64.deb
RUN gdebi -n webots_2023b_amd64.deb

RUN apt clean && rm -rf /var/lib/apt/lists/*

ENV QT_QPA_PLATFORM offscreen

COPY booster-runner-full-webots-k1-0.0.1.run .
RUN chmod +x booster-runner-full-webots-k1-0.0.1.run
ENTRYPOINT ./booster-runner-full-webots-k1-0.0.1.run
